FROM --platform=linux/arm64 python:3.8-buster AS compile

ENV DEBIAN_FRONTEND=noninteractive

# Install base build dependencies
RUN apt-get update

RUN apt-get install -y --no-install-recommends \
    build-essential
RUN apt-get install -y --no-install-recommends \
    cmake
RUN apt-get install -y --no-install-recommends \
    gfortran \
    git \
    wget \
    curl
RUN apt-get install -y --no-install-recommends \
    libatlas-base-dev \
    libjpeg-dev \
    liblapack-dev \
    libswscale-dev \
    libavcodec-dev \
    libavformat-dev \
    pkg-config \
    python3-dev \
    python3-numpy \
    zip \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Create virtual environment
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Upgrade pip and install required packages
RUN pip install --upgrade pip

# Clone and install dlib (with minimal GUI-free config)
RUN git clone -b 'v19.21' --single-branch https://github.com/davisking/dlib.git && \
    cd dlib && \
    python3 setup.py install --set BUILD_SHARED_LIBS=OFF

# Install face_recognition and OpenCV
RUN pip install flask face_recognition opencv-python-headless